sudo: require
services:
  - docker

before_install:
  - docker build -t aryankush25/my-app-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true aryankush25/my-app-docker-react npm run test
